---
output:
  pdf_document:
    highlight: default
    toc: no
  geometry: margin=1in
  html_document:
    toc: no
---

#### MAR536: Biological Statistics II
## R Laboratory Exercise 1
January 27, 2016  
Instructor: Gavin Fay, gfay@umassd.edu

Open a new R script. Save it. (name it lastname_lab1.R or something similar)  
At the top of the script, add comments with your name and lab 1. (comments are text preceded by a "`#`")  
Work in pairs or individually.  Submit your R script to Gavin before lab next week.  

1. Write code that evaluates the following when run.
$$7 + 5(4+3)$$
$$e^{-5(0.2+0.15)}$$
$$\frac{\sqrt{1+2(3+2)}}{\ln(3^2+2)}$$  

2. Create vectors using `seq()`, `rep()`, and mathematical operators.
Only use `c()` when absolutely necessary.
___hint___ Remember you can get help on a function by typing `?functionname`
- Positive integers from 1 to 99
- Odd integers between 1 and 99
- The numbers 1,1,1, 2,2,2, 3,3,3
- The numbers -5,-4,-3,-5,-4,-3,-5,-4,-3
- The fractions 1, 1/2, 1/3, 1/4, …, 1/10
- The cubes 1, 8, 27, 64, 125, 216

3. Complete the following using the vector `y`:  
$$ y <- c(3,2,15,-1,22,1,9,17,5) $$
- Display the first and last values.
- Find the last value for a vector of any length.
- Display the values that are greater than the mean of `y`.
- Display the positions (indices) of the values greater than the mean.
- Are all the values positive?
- Are any of the values equal to the mean?
- Are any of the values equal to the median?

4. The dataframe '`hills`' contains record times for Scottish hill races.  
(`hills` is in the MASS package. To load, type `library(MASS)`)  

- Display the first 5 rows of the `hills` dataframe.
- Find the fastest time.
- Display the hill races (and distance, climbs, and times) with the 3 fastest times.
- Extract and display the record time for Cairngorm.
- Find how many hill races have a climb greater than the mean.
- Display the names of the hill races that have a climb greater than the mean.
- Display the names and times of the races that are at least 10 miles long and have a climb greater than 4000 feet.  
- Find the positions (indices) of hills that either have a climb greater than 5000 feet or have a record time less than 20 minutes.  
- Find the standard deviation of the record times for all races except for the highest climb, the Bens of Jura.
- Display the range (minimum and maximum) of the average speed for the races.
- Find the race that had the fastest average speed.
- ___bonus___ Find the mean of the record times for races whose names start with letters `A` through `K`.
